"""Referee w9, claim typeclosed#0 (Theorem L+): exact end-to-end test, independent of tc4/thmL*.py.
Integer model at rank R: capacities X (ints), types = integer vectors c, 0<=c<=X, sum c = R (optionally <= R).
tau*.R = min over thresholds theta (theta_i in {positive c_i values} u {inf}) blocking every type (c_i >= theta_i
for some i) of sum_{theta_i finite} (X_i - theta_i).  [u_i = theta_i - eps is the free vector.]
Hypothesis: parts j=0,k=1; every type has 3c_i <= 2X_i for i >= 2.  Keep families with 4 tau*R > 3R.
Run the proof LITERALLY, asserting every intermediate claim, and
 * pencil branch: check Lemma 7.63 inequalities exactly + float LP realisation on the 7 line-complement cells;
 * V branch: build an EXPLICIT integer Venn realisation (scale 4) from the hand masses, trim rows to the exact
   types, and brute-force that no two vertices (or one) meet all 7 edges.
Families are generated by a hill-climb on tau* inside the hypothesis class (so near-extremal / boundary cases occur),
plus a MUTATION mode (drop the 2/3-light hypothesis) to see what breaks.
usage: python3 w9_ref_typeclosed0_e2e.py SEED NFAM [mut]
"""
import sys, random, itertools
from fractions import Fraction as F

seed = int(sys.argv[1]); NF = int(sys.argv[2]); MUT = len(sys.argv) > 3 and sys.argv[3] == 'mut'
rng = random.Random(seed)
FULL = frozenset(range(7))

def tau_R(X, C):
    p = len(X)
    cand = [sorted({c[i] for c in C if c[i] > 0}) + [None] for i in range(p)]
    best = None
    for th in itertools.product(*cand):
        if all(any(th[i] is not None and c[i] >= th[i] for i in range(p)) for c in C):
            cost = sum(X[i] - th[i] for i in range(p) if th[i] is not None)
            if best is None or cost < best: best = cost
    return best  # None impossible if C nonempty? (a type with all zeros cannot exist since sum=R>0)

def light(X, c, i): return 3 * c[i] <= 2 * X[i]

def hyp_ok(X, C): return all(light(X, c, i) for c in C for i in range(2, len(X)))

# ---- Fano (Lemma 7.63) -------------------------------------------------------------
LINES = [frozenset({i % 7, (i + 1) % 7, (i + 3) % 7}) for i in range(7)]
def fano_ok(X, rows):  # rows: list of 7 type vectors assigned to row labels 0..6 (row-Fano points)
    for i in range(len(X)):
        z = [r[i] for r in rows]
        if max(z) > X[i]: return False
        if any(2 * sum(z[r] for r in L) > 4 * X[i] for L in LINES): return False  # sum_L <= 2X
        if sum(z) > 4 * X[i]: return False
    return True

def fano_lp(X, rows):
    import numpy as np
    from scipy.optimize import linprog
    cells = [FULL - L for L in LINES]
    M = np.array([[1.0 if r in c else 0.0 for c in cells] for r in range(7)])
    for i in range(len(X)):
        z = np.array([float(r[i]) for r in rows])
        res = linprog(np.ones(7), A_ub=-M, b_ub=-z, bounds=(0, None), method='highs')
        if res.status != 0 or res.fun > X[i] + 1e-7: return False
    return True

# ---- V realisation -----------------------------------------------------------------
W = [2, 3, 4, 5]; Z = 6
VC = [frozenset({0, 1})] + [frozenset(c) for c in itertools.combinations(W + [Z], 4)] + \
     [frozenset(c) for c in ({0, 3, 4, Z}, {0, 2, 5, Z}, {1, 2, 4, Z}, {1, 3, 5, Z})]
MIXED = VC[6:]; FOURS = VC[1:6]
def v_masses(s, t):  # exact Fractions; rows 0,1 load t (c-rows), rows 2..6 load s (a-rows)
    m = {c: F(0) for c in VC}
    if 2 * t <= s:
        for c in MIXED: m[c] = F(t, 2)
        dem = {2: s - t, 3: s - t, 4: s - t, 5: s - t, 6: s - 2 * t}; T = F(sum(dem.values()), 4)
    else:
        for c in MIXED: m[c] = F(s, 4)
        m[VC[0]] = F(t) - F(s, 2)
        dem = {2: F(s, 2), 3: F(s, 2), 4: F(s, 2), 5: F(s, 2), 6: F(0)}; T = F(s, 2)
    for c in FOURS:
        om = (set(W + [Z]) - c).pop(); m[c] += T - dem[om]
    assert all(v >= 0 for v in m.values())
    return m

def realise_V(X, a, c, scale=4):
    """Build vertices part by part; rows 0,1 = type c, rows 2..6 = type a. Return (ok, info)."""
    p = len(X)
    mem = []           # membership (after trimming) of each vertex
    rowcount = [[0] * p for _ in range(7)]
    for i in range(p):
        m = v_masses(a[i], c[i])
        tot = sum(m.values())
        if tot * scale > X[i] * scale: return False, ('capacity', i, tot, X[i])
        verts = []
        for cell in VC:
            k = m[cell] * scale; assert k.denominator == 1
            verts += [set(cell) for _ in range(int(k))]
        need = [c[i] * scale] * 2 + [a[i] * scale] * 5
        for r in range(7):  # trim: keep r in the first need[r] vertices containing r
            cnt = 0
            for v in verts:
                if r in v:
                    if cnt < need[r]: cnt += 1
                    else: v.discard(r)
            if cnt < need[r]: return False, ('load', i, r)
            rowcount[r][i] = cnt
        mem += verts
    for r in range(7):
        want = (c if r < 2 else a)
        assert rowcount[r] == [w * scale for w in want]
    ms = set(frozenset(v) for v in mem)
    for u in ms:
        for v in ms:
            if (u | v) == FULL: return False, ('pierced', sorted(u), sorted(v))
    return True, len(mem)

# ---- the proof, literally ---------------------------------------------------------------
stats = {'pencil': 0, 'V': 0, 'V_nearmin': 0}
def run_proof(X, C, R):
    p = len(X); tR = tau_R(X, C); assert 4 * tR > 3 * R
    # step 0
    for e in C:
        if all(3 * e[i] <= 2 * X[i] for i in range(p)):
            d = [F(4 * X[i] - 3 * e[i], 4) for i in range(p)]
            assert all(0 <= d[i] <= X[i] for i in range(p))
            assert F(sum(X), 1) - sum(d) == F(3 * R, 4)  # cost exactly 3/4 (mass R)
            req = [cc for cc in C if all(cc[i] <= d[i] for i in range(p))]
            assert req, 'request unanswered although cost 3/4 < tau*'
            cp = req[0]
            rows = [None] * 7
            for r in range(7): rows[r] = e if r in LINES[0] else cp
            assert fano_ok(X, rows) and fano_lp(X, rows)
            stats['pencil'] += 1; return
    # step 1
    j, k = 0, 1
    A = [c for c in C if 3 * c[k] > 2 * X[k]]; B = [c for c in C if 3 * c[j] > 2 * X[j]]
    assert all(c in A or c in B for c in C)
    assert A and B, 'A or B empty'
    sj = min(c[j] for c in B); sk = min(c[k] for c in A)
    ej, ek = X[j] - sj, X[k] - sk
    assert 3 * sj >= 2 * X[j] and 3 * sk >= 2 * X[k]
    assert ej + ek >= tR  # free vector (sj-eps, sk-eps, X elsewhere)
    assert 4 * (ej + ek) > 3 * R
    assert 4 * (X[j] + X[k]) > 9 * R and 2 * X[j] <= 3 * R and 2 * X[k] <= 3 * R
    assert 4 * X[j] > 3 * R and 4 * X[k] > 3 * R
    # margins for eta
    K1 = F(X[k] - sk - (R - sj)); K2 = F(X[k]) - F(5 * sk, 4) - F(R - sj, 2)
    assert K1 > 0 and K2 > 0
    eta = min(K1, F(4, 5) * K2)
    for a in A:
        if not a[k] - sk < eta: continue
        # step 2
        cost = sum(a[i] for i in range(p) if i != k) + ek  # + eps
        assert cost <= R - a[k] + ek and cost <= R + X[k] - 2 * sk and 3 * cost <= 3 * R - X[k]
        assert 4 * cost < 3 * R and cost < tR
        wit = [c for c in C if all(c[i] <= X[i] - a[i] for i in range(p) if i != k) and c[k] < sk]
        assert wit, 'no witness'
        for c in wit:
            assert c in B and c not in A and c[k] <= R - sj
            # step 3
            for i in range(p):
                assert a[i] + c[i] <= X[i]
                assert 5 * a[i] + 2 * c[i] <= 4 * X[i], ('5/4 facet', i)
                if i != k: assert 3 * a[i] <= 2 * X[i]
            ok, info = realise_V(X, a, c)
            assert ok, info
        if a[k] == sk: stats['V'] += 1
        else: stats['V_nearmin'] += 1
    return

# ---- generator + climb ----------------------------------------------------------------
def rand_type(X, R, mode, strict_hyp=True):
    p = len(X)
    for _ in range(200):
        c = [0] * p
        if mode in 'AB':
            h = 1 if mode == 'A' else 0
            lo, hi = 2 * X[h] // 3 + 1, min(R, X[h])
            if lo > hi: return None
            c[h] = rng.randint(lo, hi)
        rest = R - sum(c)
        caps = [X[i] if (i < 2 or not strict_hyp) else (2 * X[i]) // 3 for i in range(p)]
        if mode == 'L': caps = [(2 * X[i]) // 3 for i in range(p)]
        caps = [caps[i] - c[i] for i in range(p)]
        order = list(range(p)); rng.shuffle(order)
        for _ in range(rest):
            opts = [i for i in range(p) if caps[i] > 0]
            if not opts: break
            i = rng.choice(opts); c[i] += 1; caps[i] -= 1
        if sum(c) == R and all(c[i] <= X[i] for i in range(p)):
            if mode == 'A' and not 3 * c[1] > 2 * X[1]: continue
            if mode == 'B' and not 3 * c[0] > 2 * X[0]: continue
            return tuple(c)
    return None

import os; R = int(os.environ.get('RANK', '24'))
seen = set(); nfam = 0; nmutfail = 0
while nfam < NF:
    p = rng.choice([2, 3, 3, 4])
    X = [rng.randint(3 * R // 4 + 1, 3 * R // 2), rng.randint(3 * R // 4 + 1, 3 * R // 2)] + \
        [rng.randint(0, R + R // 2) for _ in range(p - 2)]
    if rng.random() < 0.3:  # boundary capacities
        X[0] = rng.choice([X[0], 3 * R // 2, 3 * R // 4 + 1]); X[1] = rng.choice([X[1], 3 * R // 2])
    modes = ['A', 'B'] + (['L'] if rng.random() < 0.05 else [])
    C = []
    for _ in range(rng.randint(2, 6)):
        t = rand_type(X, R, rng.choice(modes), strict_hyp=not MUT)
        if t: C.append(t)
    if not C: continue
    C = list(dict.fromkeys(C))
    cur = tau_R(X, C)
    for it in range(60):  # climb tau*
        C2 = list(C); r = rng.random()
        if r < 0.4 and len(C2) > 1: C2.pop(rng.randrange(len(C2)))
        elif r < 0.7:
            t = rand_type(X, R, rng.choice(modes), strict_hyp=not MUT)
            if t: C2.append(t)
        else:
            t = rand_type(X, R, rng.choice(modes), strict_hyp=not MUT)
            if t and C2: C2[rng.randrange(len(C2))] = t
        C2 = list(dict.fromkeys(C2))
        if not C2: continue
        v = tau_R(X, C2)
        if v >= cur: C, cur = C2, v
        if 4 * cur > 3 * R:
            key = (tuple(X), tuple(sorted(C)))
            if key in seen: continue
            seen.add(key)
            if MUT and hyp_ok(X, C): continue
            try:
                run_proof(X, C, R)
            except AssertionError as ex:
                if MUT:
                    nmutfail += 1
                    if nmutfail <= 5: print('MUT failure (expected possible):', X, sorted(C), 'tau*R=', cur, ex)
                else:
                    print('FAILURE', X, sorted(C), cur, repr(ex)); raise
            nfam += 1
            if nfam % 100 == 0: print(nfam, stats, 'mutfail', nmutfail, flush=True)
            if nfam >= NF: break
print('DONE seed', seed, 'families', nfam, stats, 'mutfail', nmutfail)
